print("Hello World!")
print("Hello", "World", "Amith", 123, 3.14, True)
print("Hello", "World", "Amith", 123, 3.14, True, sep="-")
print("Hello", "World", "Amith", 123, 3.14, True, sep="|")
print("Hello", "World", "Amith", 123, 3.14, True, sep="-", end="_")
print("Pramod")
print("Hello", "World", "Amith", 123, 3.14, True, sep="-", end="")
print("Pramod")
print("Hello", "World", "Amith", 123, 3.14, True, sep="-", end="  ")
print("Pramod")
print("Hello","World","Amith",123,3.14,True,sep= "-",end="_")
print("Pramod")
print("Hello","World","Amith",123,3.14,True,sep= "-",end="_")

